### ISSUE TITLE
使用vue init webpack的时候 运行会报vueRouter not found

### ISSUE THREAD

**Issue by ZhengXiaowei** [wangdahoo/vonic-webpack-demo#7]
![image](https://user-images.githubusercontent.com/15809841/30865181-7931bb6e-a308-11e7-815d-a6e30530cb15.png)
使用vue init webpack my-project后
然后按照方式引入vonic ,然后npm run dev后报的错误 本身是按了vue-router了 
但是看作者并没有安装vue-router 后来 我又新建了项目 不安装vue-router 还是报这个错误
求解!

**Comment by ZhengXiaowei** [comment]
已解决

**Comment by linghuam** [comment]
我也遇到了同样的问题，请问你是如何解决的 @ZhengXiaowei

**Comment by ZhengXiaowei** [comment]
@linghuam 太久远了 我也忘了 不过用这个做的项目还在 你要的话 可以给你看看，应该是main.js里的配置
